name: Bench
on: push
jobs:
  test:
    name: Run Benchmarks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@004814556e37c54a2f6e31384c9e18e983317366 # v1.1.0
        with:
          deno-version: v1.x
      - run: deno task bench
